### ISSUE TITLE
Incompatibility with Snapshot 25w17a - Method Not Found [INCOMPATIBILITY]

### ISSUE THREAD

**Issue by RodrigoGCR** [haubna/PhysicsMod#1072]
# Issue Description:

Hello, while trying to use the latest version of Physics Mod (3.1.4) in Minecraft snapshot 25w17a, the game crashes. The main error seems to be:

`java.lang.NoSuchMethodError: 'void net.minecraft.class_10868.<init>(java.lang.String, com.mojang.blaze3d.textures.TextureFormat, int, int, int, int)'
    at knot//net.diebuddies.physics.PhysicsMod.loadCloth(PhysicsMod.java:465)`

This indicates that the mod is trying to call a method that does not exist in the snapshot. I have confirmed that this version of the mod works correctly in Minecraft 1.21.5, but not in the latest snapshot. Could you check if it's possible to add support for snapshots?

# Steps to Reproduce:

1. Install Minecraft snapshot 25w17a.

2. Install Fabric Loader 0.16.13.

3. Add Physics Mod 3.1.4 to the profile.

4. Launch the game.

# Technical Details:

Minecraft Version: 25w17a (snapshot)

Fabric Loader Version: 0.16.13

Physics Mod Version: 3.1.4

Operating System: Windows 11

Java Version: OpenJDK 64-Bit Server VM 21.0.3, Microsoft

Processor: 12th Gen Intel Core i5-12500H

GPU: NVIDIA GeForce RTX 3050 Laptop GPU

# Attachments:

`----` Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2025-04-22 21:17:21
Description: Initializing game

java.lang.NoSuchMethodError: 'void net.minecraft.class_10868.<init>(java.lang.String, com.mojang.blaze3d.textures.TextureFormat, int, int, int, int)'
	at knot//net.diebuddies.physics.PhysicsMod.loadCloth(PhysicsMod.java:465)
	at knot//net.minecraft.class_1060.handler$zpe000$physicsmod$constructor(class_1060.java:1027)
	at knot//net.minecraft.class_1060.<init>(class_1060.java:44)
	at knot//net.minecraft.class_310.<init>(class_310.java:548)
	at knot//net.minecraft.client.main.Main.main(Main.java:249)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ``

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.diebuddies.physics.PhysicsMod.loadCloth(PhysicsMod.java:465)
	at knot//net.minecraft.class_1060.handler$zpe000$physicsmod$constructor(class_1060.java:1027)
	at knot//net.minecraft.class_1060.<init>(class_1060.java:44)
	at knot//net.minecraft.class_310.<init>(class_310.java:548)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:API base de Windows 32 avanzado:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Biblioteca de controles de la experiencia del usuario:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.26100.2894 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.26100.3624:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.26100.3037 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DLL de API de cliente DNS:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.26100.3775 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:DLL de la biblioteca de programas de OpenGL:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		HID.DLL:Biblioteca de usuario de HID:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.26100.3775 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:API auxiliar para IP:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		IntelControlLib.dll:Intel Graphics Control Lib Runtime:1.0.213:
		KERNEL32.DLL:Archivo DLL de cliente API BASE de Windows NT:10.0.26100.3775 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Archivo DLL de cliente API BASE de Windows NT:10.0.26100.3775 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:Archivo DLL del servidor MSCTF:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		MessageBus.dll:NVIDIA Message Bus::NVIDIA Corporation
		Microsoft.Internal.WarpPal.dll
		MpOav.dll:IOfficeAntiVirus Module:4.18.25030.2 (000028f0c1f345a538ea89b768605447f1c02bdf):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.26100.2894 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		NvCamera64.dll:Camera control and photo capture:7.1.0.0:NVIDIA Corporation
		NvMessageBus.dll:NVIDIA Message Bus::NVIDIA Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE para Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Archivo DLL auxiliar del perfil de energía:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Ayudante de los datos de rendimiento DLL de Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		PhysXCommon_64.dll:PhysXCommon 32bit Dynamic Link Library:5.5.1.0:NVIDIA Corporation
		PhysXCooking_64.dll:PhysXCooking 32bit Dynamic Link Library:5.5.1.0:NVIDIA Corporation
		PhysXDevice64.dll:NVIDIA PhysX Device Module:18, 12, 7, 2:NVIDIA Corporation
		PhysXFoundation_64.dll:PhysXFoundation 32bit Dynamic Link Library:5.5.1.0:NVIDIA Corporation
		PhysXGpu_64.dll:PhysXGpu 32bit Dynamic Link Library:5.5.1.0:NVIDIA Corporation
		PhysXJniBindings_64.dll
		PhysX_64.dll:PhysX 32bit Dynamic Link Library:5.5.1.0:NVIDIA Corporation
		RPCRT4.dll:Tiempo de ejecución de llamada a procedimiento remoto:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Archivo DLL común del shell de Windows:10.0.26100.3323 (WinBuild.160101.0800):Microsoft Corporation
		Setupapi.dll:API de instalación de Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.26100.1301 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Archivo DLL de cliente API USER de Windows multiusuario:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Servicios HTTP de Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:DLL de 32 bits de Windows Socket 2.0:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		WindowsCodecs.dll:Microsoft Windows Codecs Library:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		XINPUT9_1_0.dll:Sistema de controles estándar de XNA:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Biblioteca de compatibilidad de aplicaciones cliente:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Biblioteca de primitivas criptográficas de Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.26100.3037 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM para Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		d3d11.dll:Direct3D 11 Runtime:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		d3dcompiler_47_64.dll:Direct3D HLSL Compiler for Redistribution:6.3.9600.16384 (winblue_rtm.130821-1623):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		dcomp.dll:Microsoft DirectComposition Library:10.0.26100.3775 (WinBuild.160101.0800):Microsoft Corporation
		devobj.dll:Device Information Set DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:Servicio cliente DHCP:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		drvstore.dll:Driver Store API:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:API del Administrador de ventanas de escritorio de Microsoft:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		dxgi.dll:DirectX Graphics Infrastructure:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		fwpuclnt.dll:API de modo usuario de FWP/IPsec:10.0.26100.3037 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.26100.3775 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		gpapi.dll:API de Cliente de directiva de grupo:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		icm32.dll:Microsoft Color Management Module (CMM):10.0.26100.2314 (WinBuild.160101.0800):Microsoft Corporation
		igc-default64.dll:Intel Graphics Shader Compiler for Intel(R) Graphics Accelerator:32.0.101.6127:Intel Corporation
		igc64.dll:Intel Graphics Shader Compiler for Intel(R) Graphics Accelerator:32.0.101.6127:Intel Corporation
		igd10iumd64.dll:User Mode Driver for Intel(R) Graphics Technology:32.0.101.6127:Intel Corporation
		igd10um64xe.DLL:User Mode Driver for Intel(R) Graphics Technology:32.0.101.6127:Intel Corporation
		igdgmm64.dll:User Mode Driver for Intel(R) Graphics Technology:32.0.101.6127:Intel Corporation
		imagehlp.dll:Windows NT Image Helper:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:21.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jna2860092053259905828.dll:JNA native library:7.0.2:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:21.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		msasn1.dll:ASN.1 Runtime APIs:10.0.26100.2894 (WinBuild.160101.0800):Microsoft Corporation
		mscms.dll:Archivo DLL de Sistema de coincidencias de color de Microsoft:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Proveedor de servicios de Microsoft Windows Sockets 2.0:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Proveedor de correcciones de compatibilidad (shim) de nomenclaturas de correo electrónico:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Enrutador de Windows NCrypt:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:DLL del nivel de Windows NT:10.0.26100.3775 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Proveedor MARTA de Windows NT:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		nvapi64.dll:NVIDIA NVAPI Library, Version 566.07 :32.0.15.6607:NVIDIA Corporation
		nvcuda.dll:NVIDIA CUDA Driver, Version 566.07 :32.0.15.6607:NVIDIA Corporation
		nvcuda64.dll:NVIDIA CUDA Driver, Version 566.07 :32.0.15.6607:NVIDIA Corporation
		nvdxgdmal64.dll
		nvgpucomp64.dll:NVIDIA GPU Compiler Driver, Version 566.07 :32.0.15.6607:NVIDIA Corporation
		nvldumdx.dll:NVIDIA Driver Loader, Version 566.07 :32.0.15.6607:NVIDIA Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:32.0.15.6607:NVIDIA Corporation
		nvppex.dll:NVIDIA Driver, Version 566.07 :32.0.15.6607:NVIDIA Corporation
		nvspcap64.dll:NVIDIA Game Proxy:3.28.0.412:NVIDIA Corporation
		nvwgf2umx.dll:NVIDIA D3D10 Driver, Version 566.07 :32.0.15.6607:NVIDIA Corporation
		opengl32.dll:OpenGL Client DLL:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL de objetos de rendimiento del sistema Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.26100.1301 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Biblioteca de utilidades de Shell:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Biblioteca UxTheme de Microsoft:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.26100.3775 (WinBuild.160101.0800):Microsoft Corporation
		windows.staterepositorycore.dll:Windows StateRepository API Core:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:API de almacenamiento de Microsoft WinRT:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		wintrust.dll:Microsoft Trust Verification APIs:10.0.26100.3624 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:DLL de tipos basados en Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		wldp.dll:Directiva de bloqueo de Windows:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:API Microsoft Common Controller:10.0.26100.2308 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:249)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 25w17a
	Minecraft Version ID: 25w17a
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 283279376 bytes (270 MiB) / 503316480 bytes (480 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6607
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 2048.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.101.6127
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 31364.86
	Virtual memory used (MiB): 18254.24
	Swap memory total (MiB): 23552.00
	Swap memory used (MiB): 1729.17
	Space in storage for jna.tmpdir (MiB): available: 275592.31, total: 458109.31
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 275592.31, total: 458109.31
	Space in storage for io.netty.native.workdir (MiB): available: 275592.31, total: 458109.31
	Space in storage for java.io.tmpdir (MiB): available: 275592.31, total: 458109.31
	Space in storage for workdir (MiB): available: 275592.31, total: 458109.31
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 3.0.6+mc1.21.5
			cloth-config: Cloth Config v17 18.0.145
				cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.121.1+1.21.6
			fabric-api-base: Fabric API Base 0.4.63+9ec45cd816
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.96+9ec45cd816
			fabric-biome-api-v1: Fabric Biome API (v1) 16.0.8+9ec45cd816
			fabric-block-api-v1: Fabric Block API (v1) 1.0.38+9ec45cd816
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.27+9ec45cd816
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.17+9ec45cd816
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.38+9ec45cd816
			fabric-command-api-v1: Fabric Command API (v1) 1.2.71+f71b366f16
			fabric-command-api-v2: Fabric Command API (v2) 2.2.50+9ec45cd816
			fabric-commands-v0: Fabric Commands (v0) 0.2.88+df3654b316
			fabric-content-registries-v0: Fabric Content Registries (v0) 10.0.14+c1dce21816
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.30+7f945d5b16
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.14.4+9ec45cd816
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.13+9ec45cd816
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.7.0+dff4c21b16
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.3.6+764a308e16
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.18+75fa737a16
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.26+9ec45cd816
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.14+9ec45cd816
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.71+9ec45cd816
			fabric-item-api-v1: Fabric Item API (v1) 11.3.4+9ec45cd816
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.2.10+9ec45cd816
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.64+9ec45cd816
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.62+df3654b316
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.14+9ec45cd816
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.49+3f89f5a516
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.37+9ec45cd816
			fabric-message-api-v1: Fabric Message API (v1) 6.0.34+9ec45cd816
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 5.2.0+a00fb30916
			fabric-networking-api-v1: Fabric Networking API (v1) 4.4.1+9ec45cd816
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 21.0.2+9ec45cd816
			fabric-particles-v1: Fabric Particles (v1) 4.1.2+c1dce21816
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.1.7+9ec45cd816
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.21+9ec45cd816
			fabric-renderer-api-v1: Fabric Renderer API (v1) 6.0.3+a00fb30916
			fabric-renderer-indigo: Fabric Renderer - Indigo 3.0.5+c1dce21816
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.65+73761d2e16
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.28+9ec45cd816
			fabric-rendering-v1: Fabric Rendering (v1) 12.0.2+c1dce21816
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.22+9ec45cd816
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.1.8+c1dce21816
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.49+529d3d5816
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.129+c1dce21816
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.39+9ec45cd816
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.18+9ec45cd816
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.26+529d3d5816
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.20+529d3d5816
		fabricloader: Fabric Loader 0.16.13
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.6-alpha.25.17.a
		physicsmod: Physics Mod 3.1.4
	Launched Version: fabric-loader-0.16.13-25w17a
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.07, NVIDIA Corporation
	Window size: <not initialized>
	GFLW Platform: win32
	Render Extensions: GL_ARB_buffer_storage, GL_KHR_debug, GL_ARB_vertex_attrib_binding, GL_ARB_direct_state_access
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: es_MX
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-12500H`

**Comment by haubna** [comment]
I haven't released a version for the latest snapshot yet. You will have to wait for it. Mojang is changing a lot inside their Minecraft engine causing a lot of changes on my end as well.
